/**
 * Maps platform slugs to their pixel art console icon files.
 * Icons sourced from SamuraiCowboy's icon pack.
 *
 * Each key is a possible slug (lowercase). Multiple slugs can map
 * to the same icon file. The function tries an exact match first,
 * then falls back to partial/keyword matching.
 */
const ICON_MAP: Record<string, string> = {
  // ── Nintendo ──
  nes: "nintendo-famicom.png",
  famicom: "nintendo-famicom.png",
  "famicom-disk-system": "nintendo-famicom-disk-system.png",
  fds: "nintendo-famicom-disk-system.png",
  snes: "nintendo-super-game-boy-us.png",
  "super-nintendo": "nintendo-super-game-boy-us.png",
  "super-famicom": "nintendo-super-game-boy-jp.png",
  n64: "nintendo-famicom.png",
  "nintendo-64": "nintendo-famicom.png",
  gb: "nintendo-super-game-boy-us.png",
  gbc: "nintendo-super-game-boy-us.png",
  gba: "nintendo-super-game-boy-us.png",
  "game-boy": "nintendo-super-game-boy-us.png",
  "game-boy-color": "nintendo-super-game-boy-us.png",
  "game-boy-advance": "nintendo-super-game-boy-us.png",
  "super-game-boy": "nintendo-super-game-boy-us.png",
  sgb: "nintendo-super-game-boy-us.png",
  ds: "nintendo-ds.png",
  nds: "nintendo-ds.png",
  "nintendo-ds": "nintendo-ds.png",
  "3ds": "nintendo-ds-lite.png",
  "nintendo-ds-lite": "nintendo-ds-lite.png",
  "virtual-boy": "nintendo-virtual-boy.png",
  virtualboy: "nintendo-virtual-boy.png",
  vb: "nintendo-virtual-boy.png",
  "pokemon-mini": "pkm-mini.png",
  ngc: "gc.png",

  //Microspft

  xbox: "xbox.png",

  // ── Sega ──
  genesis: "sega-genesis-us.png",
  "sega-genesis": "sega-genesis-us.png",
  "mega-drive": "sega-megadrive-eu.png",
  megadrive: "sega-megadrive-eu.png",
  "sega-mega-drive": "sega-megadrive-eu.png",
  "32x": "sega-genesis-32x-us.png",
  "sega-32x": "sega-genesis-32x-us.png",
  sega32: "sega-genesis-32x-us.png",
  "mega-drive-32x": "sega-megadrive-32x-eu.png",
  "sega-cd": "sega-genesis-cd-us.png",
  segacd: "sega-genesis-cd-us.png",
  "mega-cd": "sega-mega-drive-cd-eu.png",
  "master-system": "sega-sg-1000-mk-iii.png",
  mastersystem: "sega-sg-1000-mk-iii.png",
  "sega-master-system": "sega-sg-1000-mk-iii.png",
  sms: "sega-sg-1000-mk-iii.png",
  "sg-1000": "sega-sg-1000.png",
  sg1000: "sega-sg-1000.png",
  "sega-sg-1000": "sega-sg-1000.png",
  "game-gear": "sega-sg-1000-mk-ii.png",
  gamegear: "sega-sg-1000-mk-ii.png",
  gg: "sega-sg-1000-mk-ii.png",
  dreamcast: "sega-dreamcast.png",
  "sega-dreamcast": "sega-dreamcast.png",
  dc: "sega-dreamcast.png",
  saturn: "sega-saturn-us.png",
  "sega-saturn": "sega-saturn-us.png",
  "sega-pico": "sega-pico-us.png",
  "sc-3000": "sega-sc-3000h.png",
  "sega-sc-3000": "sega-sc-3000h.png",

  // ── Sony ──
  ps1: "sony-playstation.png",
  psx: "sony-playstation.png",
  playstation: "sony-playstation.png",
  "playstation-1": "sony-playstation.png",
  "sony-playstation": "sony-playstation.png",
  psone: "sony-playstation-one.png",
  "ps-one": "sony-playstation-one.png",
  ps2: "sony-playstation.png",
  "playstation-2": "sony-playstation.png",
  psp: "sony-psp.png",
  "playstation-portable": "sony-psp.png",
  "sony-psp": "sony-psp.png",
  "psp-slim": "sony-psp-slim.png",

  // ── NEC ──
  "tg-16": "nec-turbografx.png",
  tg16: "nec-turbografx.png",
  turbografx: "nec-turbografx.png",
  "turbografx-16": "nec-turbografx.png",
  "pc-engine": "nec-pc-engine-duo.png",
  pce: "nec-pc-engine-duo.png",
  "pc-engine-cd": "nec-pc-engine-duo-r.png",
  "turbografx-cd": "nec-turbografxcd.png",
  pcecd: "nec-turbografxcd.png",
  turboduo: "nec-turboduo.png",
  supergrafx: "nec-supergrafx.png",
  "pc-fx": "nec-pc-fx.png",
  pcfx: "nec-pc-fx.png",
  "pc-9801": "nec-pc-9801vx.png",
  pc98: "nec-pc-9801vx.png",

  // ── Atari ──
  atari8bit: "atari-800.png",
  "atari-2600": "atari-7800-version-1.png",
  atari2600: "atari-7800-version-1.png",
  a2600: "atari-7800-version-1.png",
  "atari-5200": "atari-5200-version-1.png",
  atari5200: "atari-5200-version-1.png",
  a5200: "atari-5200-version-1.png",
  "atari-7800": "atari-7800-version-1.png",
  atari7800: "atari-7800-version-1.png",
  a7800: "atari-7800-version-1.png",
  "atari-400": "atari-400.png",
  "atari-800": "atari-800.png",
  "atari-800xl": "atari-800xl.png",
  "atari-xe": "atari-65-130xe.png",
  "atari-lynx": "atari-lynx.png",
  lynx: "atari-lynx.png",
  "atari-jaguar": "atari-jaguar.png",
  jaguar: "atari-jaguar.png",
  "atari-st": "atari-st-520.png",
  atarist: "atari-st-520.png",
  "atari-xlgs": "atari-xlgs.png",

  // ── SNK ──
  "neo-geo": "snk-ngpc-carbon-black.png",
  neogeo: "snk-ngpc-carbon-black.png",
  "neo-geo-pocket": "snk-ngpc-platinum-silver.png",
  "neo-geo-pocket-color": "snk-ngpc-crystal-white.png",
  ngp: "snk-ngpc-platinum-silver.png",
  ngpc: "snk-ngpc-crystal-white.png",

  // ── Bandai ──
  wonderswan: "bandai-wonderswan.png",
  "wonderswan-color": "bandai-wonderswan-color.png",
  ws: "bandai-wonderswan.png",
  wsc: "bandai-wonderswan-color.png",
  "swan-crystal": "bandai-wonderswan-swan-crystal.png",

  // ── 3DO ──
  "3do": "3do-panasonic.png",
  "3do-goldstar": "3do-goldstar.png",
  "3do-panasonic": "3do-panasonic.png",

  // ── Commodore ──
  amiga: "amiga-500.png",
  "amiga-500": "amiga-500.png",
  "amiga-600": "amiga-600.png",
  "amiga-1200": "amiga-1200.png",
  "amiga-cd32": "amiga-cd32.png",
  cd32: "amiga-cd32.png",
  c64: "commodore-64.png",
  "commodore-64": "commodore-64.png",
  "commodore-64c": "commodore-64c.png",
  "vic-20": "commodore-vic-20.png",
  "commodore-vic-20": "commodore-vic-20.png",
  vic20: "commodore-vic-20.png",
  "cbm-8032": "commodore-cbm-8032.png",
  pet: "commodore-pet-2001.png",
  "commodore-pet": "commodore-pet-2001.png",

  // ── Amstrad ──
  "amstrad-cpc": "amstrad-cpc-464.png",
  cpc: "amstrad-cpc-464.png",
  "cpc-464": "amstrad-cpc-464.png",
  "cpc-664": "amstrad-cpc-664.png",
  "cpc-6128": "amstrad-cpc-6128.png",

  // ── Apple ──
  "apple-ii": "apple-ii.png",
  "apple-iie": "apple-iie.png",
  apple2: "apple-ii.png",

  // ── Sinclair ──
  zxs: "sinclair-zx-spectrum.png",
  zxspectrum: "sinclair-zx-spectrum.png",
  spectrum: "sinclair-zx-spectrum.png",
  "zx-81": "sinclair-zx-81.png",
  zx81: "sinclair-zx-81.png",

  // ── Sharp ──
  x68000: "sharp-x68000.png",
  "sharp-x68000": "sharp-x68000.png",
  x68k: "sharp-x68000.png",

  // ── MSX ──
  msx: "sony-msx-hb-10p.png",
  msx2: "sony-msx2-hb-f1-ii.png",
  "msx-2": "sony-msx2-hb-f1-ii.png",

  // ── Mattel ──
  intellivision: "mattel-intellivision.png",
  "mattel-intellivision": "mattel-intellivision.png",
  intv: "mattel-intellivision.png",

  // ── GCE / Vectrex ──
  vectrex: "gce-vectrex-open.png",
  "gce-vectrex": "gce-vectrex-open.png",

  // ── Coleco ──
  colecovision: "colecovision.png",
  coleco: "colecovision.png",

  // ── Magnavox ──
  "odyssey-2": "magnavox-odyssey-2.png",
  odyssey2: "magnavox-odyssey-2.png",
  "magnavox-odyssey": "magnavox-odyssey-2.png",

  // ── DOS / PC ──
  dos: "dosbox-ibm-6571.png",
  dosbox: "dosbox-ibm-6571.png",
  "ms-dos": "dosbox-ibm-6571.png",
  msdos: "dosbox-ibm-6571.png",
  pc: "dosbox-lgr-woodgrain-486.png",

  // ── ScummVM ──
  scummvm: "scummvm-maniac.png",

  // ── Tandy ──
  tandy: "tandy-color-computer-3.png",
  coco: "tandy-color-computer-3.png",
  "color-computer": "tandy-color-computer-3.png",
  "trs-80": "tandy-trs-80-model-3.png",
  trs80: "tandy-trs-80-model-3.png",

  // ── Texas Instruments ──
  "ti-99": "texas-instruments-ti-99-4a.png",
  ti99: "texas-instruments-ti-99-4a.png",
  "ti-99-4a": "texas-instruments-ti-99-4a.png",

  // ── DEC ──
  "vt-100": "dec-vt-100.png",
  vt100: "dec-vt-100.png",

  // ── Arcade (use a generic console as fallback) ──
  arcade: "arcade.png",
  mame: "arcade.png",
  "neo-geo-mvs": "arcade.png",
  cps1: "arcade.png",
  cps2: "arcade.png",
  cps3: "arcade.png",

  "tic-80": "tic.png",
};

export function getPlatformIcon(slug: string): string | null {
  const normalized = slug.toLowerCase();
  const file = ICON_MAP[normalized];
  if (file) return `/platform-icons/${file}`;
  return null;
}

/**
 * Returns all available icon filenames for browsing/debug.
 */
export const ALL_ICON_FILES = [
  "3do-goldstar.png",
  "3do-panasonic-fz-10.png",
  "3do-panasonic.png",
  "amiga-1200.png",
  "amiga-500.png",
  "amiga-600.png",
  "amiga-cd32.png",
  "amstrad-cpc-464.png",
  "amstrad-cpc-6128-plus.png",
  "amstrad-cpc-6128.png",
  "amstrad-cpc-664.png",
  "apple-ii.png",
  "apple-iie-platinum.png",
  "apple-iie.png",
  "atari-400.png",
  "atari-5200-version-1.png",
  "atari-5200-version-2.png",
  "atari-600xl.png",
  "atari-65-130xe.png",
  "atari-7800-version-1.png",
  "atari-7800-version-2.png",
  "atari-800.png",
  "atari-800xl.png",
  "atari-jaguar.png",
  "atari-lynx-2.png",
  "atari-lynx.png",
  "atari-st-1040.png",
  "atari-st-520.png",
  "atari-xlgs-with-keyboard.png",
  "atari-xlgs.png",
  "bandai-wonderswan-color.png",
  "bandai-wonderswan-swan-crystal.png",
  "bandai-wonderswan.png",
  "colecovision-cbs.png",
  "colecovision.png",
  "commodore-64.png",
  "commodore-64c.png",
  "commodore-cbm-8032.png",
  "commodore-pet-2001.png",
  "commodore-pet-4032.png",
  "commodore-vic-20.png",
  "dec-vt-100.png",
  "dosbox-ibm-6571.png",
  "dosbox-lgr-woodgrain-486.png",
  "dosbox-tandy-1000.png",
  "gce-bandai-vectrex-closed.png",
  "gce-bandai-vectrex-open.png",
  "gce-mb-vectrex-closed.png",
  "gce-mb-vectrex-open.png",
  "gce-vectrex-closed.png",
  "gce-vectrex-open.png",
  "magnavox-odyssey-2.png",
  "mattel-intellivision-ii-red-stripe.png",
  "mattel-intellivision-ii.png",
  "mattel-intellivision-intv-system-iii.png",
  "mattel-intellivision-sears-telegames-super-video-arcade.png",
  "mattel-intellivision-tandyvision.png",
  "mattel-intellivision.png",
  "nec-pc-9801vx.png",
  "nec-pc-engine-duo-r.png",
  "nec-pc-engine-duo-rx.png",
  "nec-pc-engine-duo.png",
  "nec-pc-fx.png",
  "nec-supergrafx.png",
  "nec-turboduo.png",
  "nec-turbografx.png",
  "nec-turbografxcd.png",
  "nintendo-ds-lite.png",
  "nintendo-ds.png",
  "nintendo-famicom-disk-system.png",
  "nintendo-famicom.png",
  "nintendo-super-game-boy-2.png",
  "nintendo-super-game-boy-jp.png",
  "nintendo-super-game-boy-us.png",
  "nintendo-virtual-boy.png",
  "scummvm-maniac.png",
  "sega-dreamcast-black.png",
  "sega-dreamcast.png",
  "sega-genesis-32x-us.png",
  "sega-genesis-cd-32x-us.png",
  "sega-genesis-cd-us.png",
  "sega-genesis-us.png",
  "sega-mega-drive-cd-32x-eu.png",
  "sega-mega-drive-cd-32x-jp.png",
  "sega-mega-drive-cd-eu.png",
  "sega-mega-drive-cd-jp.png",
  "sega-megadrive-32x-eu.png",
  "sega-megadrive-32x-jp.png",
  "sega-megadrive-eu.png",
  "sega-megadrive-jp.png",
  "sega-pico-jp.png",
  "sega-pico-us.png",
  "sega-saturn-jp-grey.png",
  "sega-saturn-model-2-us.png",
  "sega-saturn-us.png",
  "sega-saturn-white.png",
  "sega-sc-3000h.png",
  "sega-sg-1000-mk-ii.png",
  "sega-sg-1000-mk-iii.png",
  "sega-sg-1000.png",
  "sharp-x68000-compact.png",
  "sharp-x68000-super-hd.png",
  "sharp-x68000-xvi.png",
  "sharp-x68000.png",
  "sinclair-zx-81.png",
  "sinclair-zx-spectrum-plus-128k.png",
  "sinclair-zx-spectrum-plus-2-128k.png",
  "sinclair-zx-spectrum-plus-3-128k.png",
  "sinclair-zx-spectrum-plus-48k.png",
  "sinclair-zx-spectrum.png",
  "snk-ngpc-camo-blue.png",
  "snk-ngpc-carbon-black.png",
  "snk-ngpc-crystal-white.png",
  "snk-ngpc-platinum-blue.png",
  "snk-ngpc-platinum-silver.png",
  "snk-ngpc-stone-blue.png",
  "sony-msx-hb-10p.png",
  "sony-msx2-hb-f1-ii.png",
  "sony-playstation-one.png",
  "sony-playstation.png",
  "sony-psp-slim.png",
  "sony-psp.png",
  "tandy-color-computer-3.png",
  "tandy-trs-80-model-3.png",
  "texas-instruments-ti-99-4a-beige.png",
  "texas-instruments-ti-99-4a.png",
] as const;
